include: package:pedantic_mono/analysis_options.yaml

linter:
   rules:
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    one_member_abstracts: false
    prefer_relative_imports: true
    use_setters_to_change_properties: false
