name: exch_jpy_to_vnd_and_thb
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  pedantic_mono: any

flutter:
  uses-material-design: true

